### ISSUE TITLE
Launching on Xcode 10 

### ISSUE THREAD

**Issue by mowolf** [jondot/ReactNativeKatas#29]
Hey,

I am new to react-native and trying to get your project to work. I ran these commands and followed that [stackoverflow answer](https://stackoverflow.com/questions/37461703/print-entry-cfbundleidentifier-does-not-exist) for fixing the error I got at first: `Print: Entry, “:CFBundleIdentifier”, Does Not Exist`

This worked, to fix that issue. Overall I did the following:

```
npm install
react-native upgrade
react-native run-ios
```

That produced following result, which I was unfortunately unable to debug.

```
warning: the transform cache was reset.
Loading dependency graph, done.
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::1 - - [01/Nov/2018:12:05:02 +0000] "GET /index.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "rnk/1 CFNetwork/975.0.3 Darwin/18.0.0"
error: bundling failed: Error: The resource `/Users/Mo/Desktop/ReactNativeKatas/index.js` was not found.
    at /Users/Mo/Desktop/ReactNativeKatas/node_modules/metro/src/IncrementalBundler.js:122:24
    at gotStat (fs.js:1783:21)
    at /Users/Mo/Desktop/ReactNativeKatas/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

Is there still a way to run your project? Should I downgrade my XCode? Any help would be greatly appreciated!

**Comment by morenoh149** [comment]
what Xcode version do you have?

**Comment by mowolf** [comment]
sorry, forgot to include:
XCode 10.1
